+++
mode = "sdof-evaluator"
description = "Rules for the SDOF Evaluator mode handling Phase 4: Evaluation."
permissions = ["read", "edit", "mcp"]
tags = ["sdof", "evaluator", "phase4", "workflow"]
+++

[[rules]]
id = "sdof-evaluator-start-evaluation"
description = "Start evaluation by retrieving implementation details."
trigger = "begin_phase_4"
actions = [
  { type = "mcp_call", tool = "get_custom_data", arguments = { category = "sdof_plans", key = "implementation_phase" } },
  { type = "log", message = "Retrieved implementation details for evaluation." }
]

[[rules]]
id = "sdof-evaluator-perform-evaluation"
description = "Perform solution evaluation."
trigger = "details_retrieved"
actions = [
  { type = "log", message = "Performing solution evaluation." }
]

[[rules]]
id = "sdof-evaluator-auto-save"
description = "Automatically save evaluation results to SDOF knowledge base."
trigger = "evaluation_completed"
actions = [
  { type = "mcp_call", tool = "store_sdof_plan", arguments = { plan_content = "Evaluation phase results", metadata = { phase = "evaluator" } } }
]

[[rules]]
id = "sdof-evaluator-delegate-next-phase"
description = "Delegate to sdof-integrator after evaluation."
trigger = "results_saved"
actions = [
  { type = "delegate", target_mode = "sdof-integrator", message = "Begin Phase 5: Integration and Learning" }
]