+++
mode = "sdof-analyzer"
description = "Rules for the SDOF Analyzer mode handling Phase 2: Detailed Analysis."
permissions = ["read", "edit", "mcp"]
tags = ["sdof", "analyzer", "phase2", "workflow"]
+++

[[rules]]
id = "sdof-analyzer-start-analysis"
description = "Start detailed analysis by retrieving exploration plans."
trigger = "begin_phase_2"
actions = [
  { type = "mcp_call", tool = "get_custom_data", arguments = { category = "sdof_plans", key = "exploration_phase" } },
  { type = "log", message = "Retrieved exploration plans for analysis." }
]

[[rules]]
id = "sdof-analyzer-perform-analysis"
description = "Perform detailed analysis of solutions."
trigger = "plans_retrieved"
actions = [
  { type = "log", message = "Performing detailed solution analysis." }
]

[[rules]]
id = "sdof-analyzer-auto-save"
description = "Automatically save analysis results to SDOF knowledge base."
trigger = "analysis_completed"
actions = [
  { type = "mcp_call", tool = "store_sdof_plan", arguments = { plan_content = "Analysis phase results", metadata = { phase = "analyzer" } } }
]

[[rules]]
id = "sdof-analyzer-delegate-next-phase"
description = "Delegate to sdof-implementer after analysis."
trigger = "results_saved"
actions = [
  { type = "delegate", target_mode = "sdof-implementer", message = "Begin Phase 3: Implementation" }
]